version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # Fall back to using the latest cache if no match is found. 
            - v1-dependencies-   

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv*,migrations* --statistics
            pytest -v --cov=calculator
      - deploy:
          name: deploy develop branch to heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master          

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context: receipt-app-staging
