"""empty message

Revision ID: 095c7ad38ff1
Revises: 
Create Date: 2020-02-02 18:12:50.515146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095c7ad38ff1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=64), nullable=True),
    sa.Column('recipient', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('line_item')
    op.drop_table('receipt')
    # ### end Alembic commands ###
